### ISSUE TITLE
Add Tailwind CSS to Existing Components

### ISSUE THREAD

**Issue by Dev-Hassaan** [Dev-Hassaan/Hassaan-Portfolio#3]
### 2. **Add Tailwind CSS to Existing Components**
   - **Description**: Replace custom CSS with Tailwind CSS utility classes in existing components to simplify the styling process.
   - **Labels**: `enhancement`, `hacktoberfest`, `good first issue`
   - **Details**: Help integrate Tailwind into components, such as applying responsive classes for different screen sizes or adding hover effects.
   - **Example Tasks**:
     - Add Tailwind classes to the header component for better styling and responsiveness.
     - Update the buttons with Tailwind's built-in utility classes.
     - Implement grid layouts using Tailwind for the portfolio section.

**Comment by DinukaUdawela** [comment]
Hi can you assign me for this task

**Comment by pasanjaythilaka** [comment]
hello, can you assign me for this task?
