### ISSUE TITLE
Add Animations Using Tailwind CSS

### ISSUE THREAD

**Issue by Dev-Hassaan** [Dev-Hassaan/Hassaan-Portfolio#5]
### 4. **Add Animations Using Tailwind CSS**
   - **Description**: Add simple but smooth animations to components to enhance interactivity.
   - **Labels**: `enhancement`, `hacktoberfest`, `good first issue`
   - **Details**: Use Tailwind's built-in animation utilities to add effects like fading, sliding, or scaling.
   - **Example Tasks**:
     - Add a hover animation to portfolio cards.
     - Add animations to the progress bar using Tailwind.

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by madmaxWMFU** [comment]
Unfortunately, I don't have time to complete this task
